#ANT
BOARD_ANT_WIRELESS_DEVICE :=

#BT
BOARD_HAVE_BLUETOOTH := true
BOARD_HAVE_BLUETOOTH_QCOM := true

#FM
ifeq ($(TARGET_BOARD_TYPE),auto)
BOARD_HAVE_QCOM_FM := false
else ifeq ($(TARGET_BOARD_AUTO),true)
BOARD_HAVE_QCOM_FM := false
else
BOARD_HAVE_QCOM_FM := true
endif

ifeq ($(TARGET_BOARD_TYPE), auto)

TARGET_USE_QTI_BT_CONFIGSTORE := false
TARGET_USE_QTI_BT_SAR := false
TARGET_USE_QTI_VND_FWK_DETECT := false
else
TARGET_USE_QTI_BT_CONFIGSTORE := true
TARGET_USE_QTI_BT_SAR := true
TARGET_USE_QTI_VND_FWK_DETECT := true
endif
TARGET_USE_BT_DUN := false

ifeq ($(TARGET_USES_QMAA),true)
ifneq ($(TARGET_USES_QMAA_OVERRIDE_BLUETOOTH),true)
BOARD_HAVE_BLUETOOTH_QCOM := false
DISABLE_BT_FTM := true
endif
ifneq ($(TARGET_USES_QMAA_OVERRIDE_FM),true)
BOARD_HAVE_QCOM_FM := false
endif
endif
